server:
  port: 9011
spring:
  jpa:
    database: MySql
    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myschool?useUnicode=true&characterEncoding=utf-8&allowMutilQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: student-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
